version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lyncas
      MYSQL_PASSWORD: lyncas
      MYSQL_DATABASE: lyncasdb
      TZ: America/Sao_Paulo
    ports: 
      - 3306:3306
    networks: 
      - link
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 10

  app:
    container_name: lycas-test
    image: diogoro/lyncas-test:mysqldb
    ports: 
      - 8080:8080
    depends_on: 
      - mysql
    networks: 
      - link

networks:
  link:
    driver: bridge